import sys

with open('frontend/app/inventory/page.tsx', 'r', encoding='utf-8') as f:
    src = f.read()

start_marker = '        {/* ── 무적관리 ── */}'
end_marker   = '        {/* ── 대량 등록 ── */}'

start_idx = src.find(start_marker)
end_idx   = src.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print(f'Markers not found: start={start_idx}, end={end_idx}')
    sys.exit(1)

new_ghost = (
'        {/* ── 무적관리 ── */}\n'
'        {activeTab === "ghost" && (() => {\n'
'          const ghostDrums = allDrums.filter(d => d.returnStatus?.startsWith("무적"));\n'
'          const ghostSelected = selectedDrums.filter(d => d.returnStatus?.startsWith("무적"));\n'
'\n'
'          const ghostGrouped = (() => {\n'
'            if (ghostSortMode === "등록시간순") {\n'
'              const sorted = [...ghostDrums].sort((a, b) => ((b.registered || "").localeCompare(a.registered || "")));\n'
'              return { "전체 (등록시간순)": sorted };\n'
'            }\n'
'            const key = ghostSortMode === "섹터별" ? "sector" : ghostSortMode === "제조사별" ? "maker" : "product";\n'
'            const groups: Record<string, DrumItem[]> = {};\n'
'            for (const d of ghostDrums) {\n'
'              const k = (d as unknown as Record<string, unknown>)[key] as string ?? "(없음)";\n'
'              if (!groups[k]) groups[k] = [];\n'
'              groups[k].push(d);\n'
'            }\n'
'            for (const k of Object.keys(groups)) groups[k].sort((a, b) => (a.lot ?? "").localeCompare(b.lot ?? ""));\n'
'            return groups;\n'
'          })();\n'
'\n'
'          const ghostEntries: [string, DrumItem[]][] = ghostSortMode === "섹터별"\n'
'            ? Object.entries(ghostGrouped).sort(([a], [b]) => {\n'
'                const ai = SECTORS.indexOf(a); const bi = SECTORS.indexOf(b);\n'
'                if (ai === -1 && bi === -1) return a.localeCompare(b);\n'
'                if (ai === -1) return 1; if (bi === -1) return -1;\n'
'                return ai - bi;\n'
'              })\n'
'            : Object.entries(ghostGrouped);\n'
'\n'
'          function renderGhostDrumTable(drums: DrumItem[]) {\n'
'            return (\n'
'              <div className="overflow-x-auto rounded border border-gray-200 max-h-[450px] overflow-y-auto">\n'
'                <table className="min-w-full text-sm">\n'
'                  <thead className="bg-gray-50 sticky top-0">\n'
'                    <tr>\n'
'                      <th className="py-2 px-2 text-center w-8">\n'
'                        <input type="checkbox"\n'
'                          checked={drums.length > 0 && drums.every(d => selectedLots.has(d.lot))}\n'
'                          onChange={() => {\n'
'                            const lots = drums.map(d => d.lot);\n'
'                            const allSel = lots.every(l => selectedLots.has(l));\n'
'                            toggleAll(lots, !allSel);\n'
'                          }} />\n'
'                      </th>\n'
'                      <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">구분</th>\n'
'                      <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">LOT</th>\n'
'                      <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">품명</th>\n'
'                      <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">제조사</th>\n'
'                      {ghostSortMode !== "섹터별" && <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">섹터</th>}\n'
'                      <th className="py-2 px-3 text-left text-xs font-semibold text-gray-500">등록일</th>\n'
'                    </tr>\n'
'                  </thead>\n'
'                  <tbody>\n'
'                    {drums.map(d => {\n'
'                      const loc = d.returnStatus?.split(":")?.[1] ?? "";\n'
'                      const sel = selectedLots.has(d.lot);\n'
'                      return (\n'
'                        <tr key={d.lot} onClick={() => toggleLot(d.lot)} className={cn("border-t border-gray-100 hover:bg-purple-50 cursor-pointer transition-colors", sel && "bg-purple-50")}>\n'
'                          <td className="py-1.5 px-2 text-center" onClick={e => e.stopPropagation()}><input type="checkbox" checked={sel} onChange={() => toggleLot(d.lot)} /></td>\n'
'                          <td className="py-1.5 px-3 text-xs font-semibold text-gray-700">{loc}</td>\n'
'                          <td className="py-1.5 px-3 font-mono text-xs">{d.lot}</td>\n'
'                          <td className="py-1.5 px-3">{d.product}</td>\n'
'                          <td className="py-1.5 px-3 text-gray-600 text-xs">{d.maker}</td>\n'
'                          {ghostSortMode !== "섹터별" && <td className="py-1.5 px-3 text-gray-600 text-xs">{d.sector}</td>}\n'
'                          <td className="py-1.5 px-3 text-gray-500 text-xs">{d.registered?.slice(0, 10)}</td>\n'
'                        </tr>\n'
'                      );\n'
'                    })}\n'
'                  </tbody>\n'
'                </table>\n'
'              </div>\n'
'            );\n'
'          }\n'
'\n'
'          const showCardGrid = ghostSortMode === "섹터별" || ghostSortMode === "품목별";\n'
'\n'
'          return (\n'
'            <div>\n'
'              {/* 정렬 모드 버튼 */}\n'
'              <div className="flex flex-wrap gap-1 mb-3">\n'
'                {(["섹터별", "제조사별", "품목별", "등록시간순"] as const).map(m => (\n'
'                  <button key={m} onClick={() => { setGhostSortMode(m); setGhostActiveGroup(null); }}\n'
'                    className={cn("px-3 py-1 rounded-full text-xs font-medium transition-colors",\n'
'                      ghostSortMode === m ? "bg-purple-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"\n'
'                    )}>\n'
'                    {m}\n'
'                  </button>\n'
'                ))}\n'
'              </div>\n'
'\n'
'              {/* 액션바 */}\n'
'              {ghostSelected.length > 0 && (\n'
'                <div className="mb-4 p-3 bg-gray-50 rounded-lg border border-gray-200">\n'
'                  {editDrum ? (\n'
'                    <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">\n'
'                      <p className="text-sm font-semibold text-blue-800 mb-3">✏️ {editDrum.product} ({editDrum.lot}) 정보 수정</p>\n'
'                      <div className="grid grid-cols-2 gap-3 mb-3">\n'
'                        <div><label className="text-xs text-gray-500 mb-1 block">LOT</label><input value={editFields.lot} onChange={e => setEditFields(p => ({ ...p, lot: e.target.value }))} className="w-full border rounded px-2 py-1.5 text-sm" /></div>\n'
'                        <div><label className="text-xs text-gray-500 mb-1 block">품명</label><input value={editFields.product} onChange={e => setEditFields(p => ({ ...p, product: e.target.value }))} className="w-full border rounded px-2 py-1.5 text-sm" /></div>\n'
'                        <div><label className="text-xs text-gray-500 mb-1 block">제조사</label><select value={editFields.maker} onChange={e => setEditFields(p => ({ ...p, maker: e.target.value }))} className="w-full border rounded px-2 py-1.5 text-sm">{MAKER_LIST.map(m => <option key={m}>{m}</option>)}</select></div>\n'
'                        <div><label className="text-xs text-gray-500 mb-1 block">섹터</label><select value={editFields.sector} onChange={e => setEditFields(p => ({ ...p, sector: e.target.value }))} className="w-full border rounded px-2 py-1.5 text-sm">{SECTORS.map(s => <option key={s}>{s}</option>)}{editFields.sector === "창고주위" && <option key="창고주위">창고주위</option>}</select></div>\n'
'                      </div>\n'
'                      <div className="mb-3">\n'
'                        <label className="text-xs text-gray-500 mb-1 block">⚫ 무적 구분</label>\n'
'                        <div className="flex gap-4">\n'
'                          {["인천", "당진"].map(loc => (\n'
'                            <label key={loc} className="flex items-center gap-1.5 cursor-pointer">\n'
'                              <input type="radio" checked={editFields.ghostLoc === loc} onChange={() => setEditFields(f => ({ ...f, ghostLoc: loc }))} />\n'
'                              <span className="text-sm font-medium">{loc}</span>\n'
'                            </label>\n'
'                          ))}\n'
'                        </div>\n'
'                      </div>\n'
'                      <div className="flex gap-2">\n'
'                        <Button onClick={doEditSave} loading={actionLoading}>💾 저장</Button>\n'
'                        <Button variant="secondary" onClick={() => setEditDrum(null)}>취소</Button>\n'
'                      </div>\n'
'                    </div>\n'
'                  ) : (\n'
'                    <div className="flex flex-wrap gap-2 items-center">\n'
'                      <span className="text-sm text-gray-600">{ghostSelected.length}드럼 선택됨</span>\n'
'                      <Button onClick={() => setConfirmType("checkout")} loading={actionLoading}>라인입고 ({ghostSelected.length})</Button>\n'
'                      {ghostSelected.length === 1 && (\n'
'                        <Button variant="secondary" onClick={() => {\n'
'                          const d = ghostSelected[0];\n'
'                          setEditDrum(d);\n'
'                          setEditFields({ lot: d.lot, product: d.product, maker: d.maker, sector: d.sector ?? SECTORS[0], remark: d.remark === "신규" ? "" : (d.remark ?? ""), ghostLoc: d.returnStatus?.split(":")?.[1] ?? "" });\n'
'                        }}>✏️ 정보 수정</Button>\n'
'                      )}\n'
'                      <Button variant="secondary" onClick={clearSelection}>선택 해제</Button>\n'
'                    </div>\n'
'                  )}\n'
'                  {confirmType === "checkout" && (\n'
'                    <div className="mt-3 flex gap-2">\n'
'                      <Button onClick={() => doAction(confirmType)} loading={actionLoading}>✅ 라인입고 확인</Button>\n'
'                      <Button variant="secondary" onClick={() => setConfirmType(null)}>❌ 취소</Button>\n'
'                    </div>\n'
'                  )}\n'
'                </div>\n'
'              )}\n'
'\n'
'              {ghostDrums.length === 0 ? (\n'
'                <p className="text-sm text-gray-400 text-center py-12">무적 드럼 없음</p>\n'
'              ) : showCardGrid ? (\n'
'                <div>\n'
'                  {(() => {\n'
'                    const rows: [string, DrumItem[]][][] = [];\n'
'                    for (let i = 0; i < ghostEntries.length; i += 3) rows.push(ghostEntries.slice(i, i + 3));\n'
'                    return rows.map((row, ri) => (\n'
'                      <div key={ri}>\n'
'                        <div className="grid grid-cols-3 gap-3 mb-2">\n'
'                          {row.map(([key, drums]) => {\n'
'                            const selCnt = drums.filter(d => selectedLots.has(d.lot)).length;\n'
'                            const isActive = ghostActiveGroup === key;\n'
'                            return (\n'
'                              <button key={key} onClick={() => setGhostActiveGroup(isActive ? null : key)}\n'
'                                className={cn("p-3 rounded-lg border text-left transition-colors text-sm",\n'
'                                  isActive\n'
'                                    ? "bg-blue-50 border-blue-400 text-blue-800"\n'
'                                    : "bg-white border-gray-200 hover:border-purple-300 hover:bg-purple-50 text-gray-700"\n'
'                                )}>\n'
'                                <div className="font-semibold truncate">{ghostSortMode === "섹터별" ? "⚫ " : ""}{key}</div>\n'
'                                <div className="text-xs text-gray-500 mt-0.5">\n'
'                                  {drums.length}드럼\n'
'                                  {selCnt > 0 && <span className="ml-2 text-purple-600 font-medium">✓{selCnt}</span>}\n'
'                                </div>\n'
'                              </button>\n'
'                            );\n'
'                          })}\n'
'                          {row.length < 3 && Array.from({ length: 3 - row.length }).map((_, i) => <div key={i} />)}\n'
'                        </div>\n'
'                        {row.some(([k]) => k === ghostActiveGroup) && ghostActiveGroup && ghostGrouped[ghostActiveGroup] && (\n'
'                          <div className="mb-4 rounded-lg border-l-4 border-blue-500 bg-blue-50/50 p-3">\n'
'                            <span className="font-semibold text-blue-800 text-sm block mb-3">\n'
'                              {ghostSortMode === "섹터별" ? "⚫ " : ""}{ghostActiveGroup} — {ghostGrouped[ghostActiveGroup].length}드럼\n'
'                            </span>\n'
'                            {renderGhostDrumTable(ghostGrouped[ghostActiveGroup])}\n'
'                          </div>\n'
'                        )}\n'
'                      </div>\n'
'                    ));\n'
'                  })()}\n'
'                </div>\n'
'              ) : ghostSortMode === "제조사별" ? (\n'
'                <div className="space-y-2">\n'
'                  {ghostEntries.map(([key, drums]) => (\n'
'                    <details key={key} className="border border-gray-200 rounded-lg">\n'
'                      <summary className="px-4 py-2.5 cursor-pointer select-none font-medium text-sm hover:bg-gray-50">\n'
'                        {key} — {drums.length}드럼\n'
'                        {drums.filter(d => selectedLots.has(d.lot)).length > 0 &&\n'
'                          <span className="ml-2 text-purple-600 text-xs">✓{drums.filter(d => selectedLots.has(d.lot)).length}</span>}\n'
'                      </summary>\n'
'                      <div className="p-3 border-t border-gray-100">\n'
'                        {renderGhostDrumTable(drums)}\n'
'                      </div>\n'
'                    </details>\n'
'                  ))}\n'
'                </div>\n'
'              ) : (\n'
'                renderGhostDrumTable(ghostEntries.flatMap(([, d]) => d))\n'
'              )}\n'
'            </div>\n'
'          );\n'
'        })()}\n'
'\n'
)

result = src[:start_idx] + new_ghost + src[end_idx:]

with open('frontend/app/inventory/page.tsx', 'w', encoding='utf-8') as f:
    f.write(result)

print('Done, file size:', len(result))
